In [11]:
import torch

In [12]:
exa = torch.Tensor([[1,2,3,4],[0,1,2,3],[2,3,4,5]])
mem = torch.Tensor([[1,2,3,4], [0,1,2,3]])

In [13]:
matches = []
for ex in torch.split(exa, 1, dim=0):
    memmatch = []
    for me in torch.split(mem, 1, dim=0):
        memmatch.append(((ex-me)**2).mean())
        print("==========")
        print(f"Memory  : {me}")
        print(f"Example : {ex}")
        print(f"diff    : {ex-me}")
        print(f"diff**2 : {(ex-me)**2}")
        print(f"mse     : {((ex-me)**2).mean()}")
    matches.append(memmatch)

Memory  : tensor([[1., 2., 3., 4.]])
Example : tensor([[1., 2., 3., 4.]])
diff    : tensor([[0., 0., 0., 0.]])
diff**2 : tensor([[0., 0., 0., 0.]])
mse     : 0.0
Memory  : tensor([[0., 1., 2., 3.]])
Example : tensor([[1., 2., 3., 4.]])
diff    : tensor([[1., 1., 1., 1.]])
diff**2 : tensor([[1., 1., 1., 1.]])
mse     : 1.0
Memory  : tensor([[1., 2., 3., 4.]])
Example : tensor([[0., 1., 2., 3.]])
diff    : tensor([[-1., -1., -1., -1.]])
diff**2 : tensor([[1., 1., 1., 1.]])
mse     : 1.0
Memory  : tensor([[0., 1., 2., 3.]])
Example : tensor([[0., 1., 2., 3.]])
diff    : tensor([[0., 0., 0., 0.]])
diff**2 : tensor([[0., 0., 0., 0.]])
mse     : 0.0
Memory  : tensor([[1., 2., 3., 4.]])
Example : tensor([[2., 3., 4., 5.]])
diff    : tensor([[1., 1., 1., 1.]])
diff**2 : tensor([[1., 1., 1., 1.]])
mse     : 1.0
Memory  : tensor([[0., 1., 2., 3.]])
Example : tensor([[2., 3., 4., 5.]])
diff    : tensor([[2., 2., 2., 2.]])
diff**2 : tensor([[4., 4., 4., 4.]])
mse     : 4.0


In [14]:
matches

[[tensor(0.), tensor(1.)], [tensor(1.), tensor(0.)], [tensor(1.), tensor(4.)]]

In [15]:
[[((ex-me)**2).mean() for me in torch.split(mem, 1, dim=0)] for ex in torch.split(exa, 1, dim=0)]

[[tensor(0.), tensor(1.)], [tensor(1.), tensor(0.)], [tensor(1.), tensor(4.)]]

In [16]:
torch.Tensor([[((ex-me)**2).mean() for me in torch.split(mem, 1, dim=0)] for ex in torch.split(exa, 1, dim=0)])

tensor([[0., 1.],
        [1., 0.],
        [1., 4.]])

In [17]:
matches = []
for ex in torch.split(exa, 1, dim=0):
    memmatch = []
    for me in torch.split(mem, 1, dim=0):
        memmatch.append(((ex-me)**2).mean())
        print("==========")
        print(f"Memory  : {me}")
        print(f"Example : {ex}")
        print(f"diff    : {ex-me}")
        print(f"diff**2 : {(ex-me)**2}")
        print(f"mse     : {((ex-me)**2).mean()}")
    print(memmatch)
    matches.append(torch.stack(memmatch, 0))

Memory  : tensor([[1., 2., 3., 4.]])
Example : tensor([[1., 2., 3., 4.]])
diff    : tensor([[0., 0., 0., 0.]])
diff**2 : tensor([[0., 0., 0., 0.]])
mse     : 0.0
Memory  : tensor([[0., 1., 2., 3.]])
Example : tensor([[1., 2., 3., 4.]])
diff    : tensor([[1., 1., 1., 1.]])
diff**2 : tensor([[1., 1., 1., 1.]])
mse     : 1.0
[tensor(0.), tensor(1.)]
Memory  : tensor([[1., 2., 3., 4.]])
Example : tensor([[0., 1., 2., 3.]])
diff    : tensor([[-1., -1., -1., -1.]])
diff**2 : tensor([[1., 1., 1., 1.]])
mse     : 1.0
Memory  : tensor([[0., 1., 2., 3.]])
Example : tensor([[0., 1., 2., 3.]])
diff    : tensor([[0., 0., 0., 0.]])
diff**2 : tensor([[0., 0., 0., 0.]])
mse     : 0.0
[tensor(1.), tensor(0.)]
Memory  : tensor([[1., 2., 3., 4.]])
Example : tensor([[2., 3., 4., 5.]])
diff    : tensor([[1., 1., 1., 1.]])
diff**2 : tensor([[1., 1., 1., 1.]])
mse     : 1.0
Memory  : tensor([[0., 1., 2., 3.]])
Example : tensor([[2., 3., 4., 5.]])
diff    : tensor([[2., 2., 2., 2.]])
diff**2 : tensor([[4., 4.

In [18]:
torch.stack(matches)

tensor([[0., 1.],
        [1., 0.],
        [1., 4.]])

In [21]:
matches = []
for ex in torch.split(exa, 1, dim=0):
    memmatch = ((ex-mem)**2).mean(1)
    matches.append(memmatch)
torch.stack(matches)

tensor([[0., 1.],
        [1., 0.],
        [1., 4.]])